steps:
  # بناء صورة Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '$_IMAGE_TAG', '.']

# تحديد الصورة التي سيتم دفعها للـ Artifact Registry
images:
  - '$_IMAGE_TAG'

# الإعدادات الإجبارية لتجاوز سياسات الـ Org Policy
options:
  logging: CLOUD_LOGGING_ONLY
  # تحديد حساب الخدمة الذي سيقوم بالبناء
  serviceAccount: 'projects/project-82256888-675b-4d03-af9/serviceAccounts/cloud-run-deployer-903@project-82256888-675b-4d03-af9.iam.gserviceaccount.com'