name: cd

on: 
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      TURSO_AUTH_TOKEN: ${{ secrets.TURSO_AUTH_TOKEN }}

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build the app
        run: npm run build

      - name: Authenticate to GCP
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/830778851432/locations/global/workloadIdentityPools/notely-pool-new/providers/notely-provider'
          service_account: 'cloud-run-deployer@project-82256888-675b-4d03-af9.iam.gserviceaccount.com'
          audience: 'repo:darxx03eh/learn-cicd-typescript-starter'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v3

      - name: Build and Push to Artifact Registry
        run: |
          gcloud builds submit \
            --tag us-central1-docker.pkg.dev/project-82256888-675b-4d03-af9/notely-ar-repox/notely:latest \
            --service-account=projects/project-82256888-675b-4d03-af9/serviceAccounts/cloud-run-deployer@project-82256888-675b-4d03-af9.iam.gserviceaccount.com \
            --project=project-82256888-675b-4d03-af9 \
            .

      - name: Run database migrations
        run: npm run db:migrate

      - name: Deploy to Cloud Run
        run: gcloud run deploy notely --image us-central1-docker.pkg.dev/project-82256888-675b-4d03-af9/notely-ar-repox/notely:latest --region us-central1 --allow-unauthenticated --project project-82256888-675b-4d03-af9 --max-instances=4